USE [master];
GO

IF DB_ID(N'SAP_Service') IS NOT NULL
BEGIN
    ALTER DATABASE [SAP_Service] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [SAP_Service];
END
GO

CREATE DATABASE [SAP_Service];
GO
